server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
logging:
  file: logs/app.log
